omment:
  layout: header, changes, diff, sunburst

coverage:
  precision: 2
  round: down
  range: "70...100"
  ignore:
    - 3rdparty/.*
    - .*/test/.*
  status:
    project:
      default: "warning"
      patch: "warning"
    patch:
      default: "warning"
      range: "70...100"